import { db } from '@/db/drizzle/db';
import { ProductTable } from './schema';

async function seedProducts() {
  console.log('Seeding products...');

  await db.insert(ProductTable).values([
    {
      name: 'Лаптоп Lenovo IdeaPad Slim 5 13ARP10',
      sku: generateRandomSku(),
      sn: null,
      price: 1799.0,
      salePrice: null,
      deliveryPrice: 1550.0,
      quantity: 3,
      createdAt: new Date('2025-05-06T16:30:03'),
      updatedAt: new Date('2025-05-06T16:30:03'),
      brandId: null,
    },
    {
      name: 'Смартфон Samsung Galaxy A54',
      sku: generateRandomSku(),
      sn: null,
      price: 799.0,
      salePrice: null,
      deliveryPrice: 650.0,
      quantity: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Монитор Dell UltraSharp U2723QE',
      sku: generateRandomSku(),
      sn: null,
      price: 1129.0,
      salePrice: null,
      deliveryPrice: 950.0,
      quantity: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Принтер HP LaserJet M110we',
      sku: generateRandomSku(),
      sn: null,
      price: 249.0,
      salePrice: null,
      deliveryPrice: 210.0,
      quantity: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Таблет Apple iPad 10.2" 64GB',
      sku: generateRandomSku(),
      sn: null,
      price: 1049.0,
      salePrice: null,
      deliveryPrice: 900.0,
      quantity: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Клавиатура Logitech MX Keys',
      sku: generateRandomSku(),
      sn: null,
      price: 219.0,
      salePrice: null,
      deliveryPrice: 180.0,
      quantity: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Мишка Logitech MX Master 3S',
      sku: generateRandomSku(),
      sn: null,
      price: 189.0,
      salePrice: null,
      deliveryPrice: 150.0,
      quantity: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Уеб камера Logitech C920',
      sku: generateRandomSku(),
      sn: null,
      price: 159.0,
      salePrice: null,
      deliveryPrice: 130.0,
      quantity: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Външен диск Seagate 2TB',
      sku: generateRandomSku(),
      sn: null,
      price: 129.0,
      salePrice: null,
      deliveryPrice: 110.0,
      quantity: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'SSD диск Samsung 980 1TB',
      sku: generateRandomSku(),
      sn: null,
      price: 159.0,
      salePrice: null,
      deliveryPrice: 140.0,
      quantity: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Захранване Seasonic 750W',
      sku: generateRandomSku(),
      sn: null,
      price: 229.0,
      salePrice: null,
      deliveryPrice: 200.0,
      quantity: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Дънна платка ASUS ROG B550-F',
      sku: generateRandomSku(),
      sn: null,
      price: 369.0,
      salePrice: null,
      deliveryPrice: 330.0,
      quantity: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Процесор AMD Ryzen 5 5600X',
      sku: generateRandomSku(),
      sn: null,
      price: 359.0,
      salePrice: null,
      deliveryPrice: 310.0,
      quantity: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Видеокарта NVIDIA RTX 4060',
      sku: generateRandomSku(),
      sn: null,
      price: 639.0,
      salePrice: null,
      deliveryPrice: 590.0,
      quantity: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'RAM памет Kingston 16GB DDR4 3200MHz',
      sku: generateRandomSku(),
      sn: null,
      price: 89.0,
      salePrice: null,
      deliveryPrice: 75.0,
      quantity: 12,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Геймърски стол DXRacer Formula',
      sku: generateRandomSku(),
      sn: null,
      price: 499.0,
      salePrice: null,
      deliveryPrice: 420.0,
      quantity: 4,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Звукoва карта Focusrite Scarlett 2i2',
      sku: generateRandomSku(),
      sn: null,
      price: 329.0,
      salePrice: null,
      deliveryPrice: 290.0,
      quantity: 3,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Микрофон Blue Yeti Blackout',
      sku: generateRandomSku(),
      sn: null,
      price: 259.0,
      salePrice: null,
      deliveryPrice: 230.0,
      quantity: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Графичен таблет Wacom Intuos S',
      sku: generateRandomSku(),
      sn: null,
      price: 179.0,
      salePrice: null,
      deliveryPrice: 150.0,
      quantity: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Рутер TP-Link Archer AX23',
      sku: generateRandomSku(),
      sn: null,
      price: 139.0,
      salePrice: null,
      deliveryPrice: 120.0,
      quantity: 8,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Bluetooth слушалки Sony WH-CH720N',
      sku: generateRandomSku(),
      sn: null,
      price: 269.0,
      salePrice: null,
      deliveryPrice: 230.0,
      quantity: 7,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Четец за книги Amazon Kindle 11th Gen',
      sku: generateRandomSku(),
      sn: null,
      price: 199.0,
      salePrice: null,
      deliveryPrice: 175.0,
      quantity: 6,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Настолен компютър Acer Aspire TC',
      sku: generateRandomSku(),
      sn: null,
      price: 1149.0,
      salePrice: null,
      deliveryPrice: 1000.0,
      quantity: 2,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Зарядно устройство Anker Nano II 65W',
      sku: generateRandomSku(),
      sn: null,
      price: 89.0,
      salePrice: null,
      deliveryPrice: 75.0,
      quantity: 10,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
    {
      name: 'Вентилатор за процесор Noctua NH-D15',
      sku: generateRandomSku(),
      sn: null,
      price: 199.0,
      salePrice: null,
      deliveryPrice: 170.0,
      quantity: 5,
      createdAt: new Date(),
      updatedAt: new Date(),
      brandId: null,
    },
  ]);

  console.log('✅ Products seeded.');
}

seedProducts()
  .catch((err) => {
    console.error('❌ Product seeding failed:', err);
    process.exit(1);
  })
  .finally(() => {
    process.exit(0);
  });

function generateRandomSku(length = 8): string {
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789';
  let sku = '';
  for (let i = 0; i < length; i++) {
    sku += chars.charAt(Math.floor(Math.random() * chars.length));
  }
  return sku;
}
