import type { Metadata } from 'next';
import './globals.css';
import Header from '@/components/Header';
import { ThemeScript } from '@/lib/themeScript';
import { ToastProvider } from '@/components/ui/toast-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning={true}>
      <head>
        <ThemeScript />
      </head>
      <body className="">
        <Header />
        <ToastProvider>{children}</ToastProvider>
      </body>
    </html>
  );
}
