import type { Metadata } from 'next';
import './globals.css';
import { ThemeScript } from '@/lib/themeScript';
import { Suspense } from 'react';
import { Toaster } from '@/components/ui/sonner';
import { ThemeProvider } from '@/components/ui/theme-provider';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense>
      <html lang="en" suppressHydrationWarning={true}>
        <head>
          <ThemeScript />
        </head>
        <body className="">
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <Toaster position="top-center" />
            {/* <Header /> */}
            {children}
          </ThemeProvider>
        </body>
      </html>
    </Suspense>
  );
}
